version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: isrc-metadata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    restart: always
    expose:
      - '5432'

  api:
    build:
      context: .
    image: lemmi/isrc-metadata:latest
    depends_on:
      - db
    ports:
      - '4000:4000'

  swagger:
    image: swaggerapi/swagger-ui
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ./openapi.yml:/openapi.yml
    environment:
      SWAGGER_JSON: /openapi.yml
